In [1]:
import pandas as pd
import numpy as np

In [3]:
df=pd.read_csv("https://raw.githubusercontent.com/dsrscientist/dataset3/main/glass.csv")
df

URLError: <urlopen error [WinError 10061] No connection could be made because the target machine actively refused it>

In [14]:
y=df["1.1"]
y.head()

0    1
1    1
2    1
3    1
4    1
Name: 1.1, dtype: int64

In [20]:
df.columns=["id","RI","Na","Mg","Al","Si","K","Ca","Ba","Fe","Type"]

In [21]:
df

id       RI     Na    Mg    Al     Si     K    Ca    Ba    Fe  Type
0      2  1.51761  13.89  3.60  1.36  72.73  0.48  7.83  0.00  0.00     1
1      3  1.51618  13.53  3.55  1.54  72.99  0.39  7.78  0.00  0.00     1
2      4  1.51766  13.21  3.69  1.29  72.61  0.57  8.22  0.00  0.00     1
3      5  1.51742  13.27  3.62  1.24  73.08  0.55  8.07  0.00  0.00     1
4      6  1.51596  12.79  3.61  1.62  72.97  0.64  8.07  0.00  0.26     1
..   ...      ...    ...   ...   ...    ...   ...   ...   ...   ...   ...
208  210  1.51623  14.14  0.00  2.88  72.61  0.08  9.18  1.06  0.00     7
209  211  1.51685  14.92  0.00  1.99  73.06  0.00  8.40  1.59  0.00     7
210  212  1.52065  14.36  0.00  2.02  73.42  0.00  8.44  1.64  0.00     7
211  213  1.51651  14.38  0.00  1.94  73.61  0.00  8.48  1.57  0.00     7
212  214  1.51711  14.23  0.00  2.08  73.36  0.00  8.62  1.67  0.00     7

[213 rows x 11 columns]

In [22]:
Y=df["Type"]
Y.head()

0    1
1    1
2    1
3    1
4    1
Name: Type, dtype: int64

In [23]:
df=df.drop("Type",axis=1)
df.head()

id       RI     Na    Mg    Al     Si     K    Ca   Ba    Fe
0   2  1.51761  13.89  3.60  1.36  72.73  0.48  7.83  0.0  0.00
1   3  1.51618  13.53  3.55  1.54  72.99  0.39  7.78  0.0  0.00
2   4  1.51766  13.21  3.69  1.29  72.61  0.57  8.22  0.0  0.00
3   5  1.51742  13.27  3.62  1.24  73.08  0.55  8.07  0.0  0.00
4   6  1.51596  12.79  3.61  1.62  72.97  0.64  8.07  0.0  0.26

In [24]:
from sklearn import preprocessing
x=df.values
min_max_scaler=preprocessing.MinMaxScaler()
x_scaled=min_max_scaler.fit_transform(x)
df=pd.DataFrame(x_scaled)
df

0         1         2         3         4         5         6  \
0    0.000000  0.283582  0.475188  0.904523  0.333333  0.521429  0.077295   
1    0.004717  0.220808  0.421053  0.891960  0.389408  0.567857  0.062802   
2    0.009434  0.285777  0.372932  0.927136  0.311526  0.500000  0.091787   
3    0.014151  0.275241  0.381955  0.909548  0.295950  0.583929  0.088567   
4    0.018868  0.211150  0.309774  0.907035  0.414330  0.564286  0.103060   
..        ...       ...       ...       ...       ...       ...       ...   
208  0.981132  0.223003  0.512782  0.000000  0.806854  0.500000  0.012882   
209  0.985849  0.250219  0.630075  0.000000  0.529595  0.580357  0.000000   
210  0.990566  0.417032  0.545865  0.000000  0.538941  0.644643  0.000000   
211  0.995283  0.235294  0.548872  0.000000  0.514019  0.678571  0.000000   
212  1.000000  0.261633  0.526316  0.000000  0.557632  0.633929  0.000000   

            7         8         9  
0    0.223048  0.000000  0.000000  
1    0.218401  0.000000  0.000000  
2    0.259294  0.000000  0.000000  
3    0.245353  0.000000  0.000000  
4    0.245353  0.000000  0.509804  
..        ...       ...       ...  
208  0.348513  0.336508  0.000000  
209  0.276022  0.504762  0.000000  
210  0.279740  0.520635  0.000000  
211  0.283457  0.498413  0.000000  
212  0.296468  0.530159  0.000000  

[213 rows x 10 columns]

In [25]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(df,Y,test_size=0.30,random_state=42)
print(x_train.shape)


(149, 10)


In [26]:
pip install pydotplus

Note: you may need to restart the kernel to use updated packages.Collecting pydotplus
  Created wheel for pydotplus: filename=pydotplus-2.0.2-py3-none-any.whl size=24575 sha256=756790890b666232beb4daac60ddc167846152d21bd621c3f95be3d46cbd4842
  Stored in directory: c:\users\skalk\appdata\local\pip\cache\wheels\89\e5\de\6966007cf223872eedfbebbe0e074534e72e9128c8fd4b55eb
Successfully built pydotplus



In [29]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score
clf=DecisionTreeClassifier(criterion="entropy")
clf=clf.fit(x_train,y_train)
y_pred=clf.predict(x_test)
accuracy_score(y_test,y_pred)

0.9375

In [35]:
from sklearn.metrics import mean_squared_error
import math
clf=DecisionTreeClassifier()
clf.fit(x_train,y_train)
ypred=clf.predict(x_test)
asc=accuracy_score(y_test,ypred)
mse=mean_squared_error(y_test,ypred)
rmse=math.sqrt(mse)
print(asc,mse,rmse)

0.96875 0.265625 0.5153882032022076


In [36]:
df.fillna(df.mean(),inplace=True)
df

0         1         2         3         4         5         6  \
0    0.000000  0.283582  0.475188  0.904523  0.333333  0.521429  0.077295   
1    0.004717  0.220808  0.421053  0.891960  0.389408  0.567857  0.062802   
2    0.009434  0.285777  0.372932  0.927136  0.311526  0.500000  0.091787   
3    0.014151  0.275241  0.381955  0.909548  0.295950  0.583929  0.088567   
4    0.018868  0.211150  0.309774  0.907035  0.414330  0.564286  0.103060   
..        ...       ...       ...       ...       ...       ...       ...   
208  0.981132  0.223003  0.512782  0.000000  0.806854  0.500000  0.012882   
209  0.985849  0.250219  0.630075  0.000000  0.529595  0.580357  0.000000   
210  0.990566  0.417032  0.545865  0.000000  0.538941  0.644643  0.000000   
211  0.995283  0.235294  0.548872  0.000000  0.514019  0.678571  0.000000   
212  1.000000  0.261633  0.526316  0.000000  0.557632  0.633929  0.000000   

            7         8         9  
0    0.223048  0.000000  0.000000  
1    0.218401  0.000000  0.000000  
2    0.259294  0.000000  0.000000  
3    0.245353  0.000000  0.000000  
4    0.245353  0.000000  0.509804  
..        ...       ...       ...  
208  0.348513  0.336508  0.000000  
209  0.276022  0.504762  0.000000  
210  0.279740  0.520635  0.000000  
211  0.283457  0.498413  0.000000  
212  0.296468  0.530159  0.000000  

[213 rows x 10 columns]

In [41]:
from sklearn.datasets import load_digits
from sklearn.linear_model import Perceptron
clf=Perceptron(tol=1e-3,random_state=0)
clf.fit(x_train,y_train)
clf.score(x_test,y_test)

0.765625

In [49]:
from sklearn.neural_network import MLPClassifier
classifier=MLPClassifier(solver='lbfgs', alpha=1e-5, hidden_layer_sizes=(5, 2), random_state=1)
classifier.fit(x_train,y_train)

C:\Users\skalk\anaconda3\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:549: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_result("lbfgs", opt_res, self.max_iter)


MLPClassifier(alpha=1e-05, hidden_layer_sizes=(5, 2), random_state=1,
              solver='lbfgs')

In [50]:
y_pred=classifier.predict(x_test)

In [51]:
from sklearn.metrics import classification_report,confusion_matrix
print(confusion_matrix(y_test,y_pred))
print(classification_report(y_test,y_pred))

[[17  1  0  0  0  0]
 [ 0 24  0  0  0  0]
 [ 0  0  4  0  0  0]
 [ 0  0  2  2  0  0]
 [ 0  0  0  1  2  0]
 [ 0  0  0  0  2  9]]
              precision    recall  f1-score   support

           1       1.00      0.94      0.97        18
           2       0.96      1.00      0.98        24
           3       0.67      1.00      0.80         4
           5       0.67      0.50      0.57         4
           6       0.50      0.67      0.57         3
           7       1.00      0.82      0.90        11

    accuracy                           0.91        64
   macro avg       0.80      0.82      0.80        64
weighted avg       0.92      0.91      0.91        64



In [52]:
from sklearn.datasets import load_iris
from sklearn.linear_model import LogisticRegression
clf=LogisticRegression(random_state=0,solver='lbfgs',
                      multi_class='multinomial').fit(x_train,y_train)

In [53]:
clf.score(x_test,y_test)

0.734375

In [56]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import mean_squared_error
from math import sqrt
clf=RandomForestClassifier(n_estimators=150,max_depth=3,random_state=0)
clf.fit(x_train,y_train)
ypred=clf.predict(x_test)
accuracy_score(y_test,ypred)
asc=accuracy_score(y_test,y_pred)
mse=mean_squared_error(y_test,y_pred)
rmse=sqrt(mse)
print(asc,mse,rmse)

0.90625 0.1875 0.4330127018922193


In [1]:
import numpy as np 
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.base import TransformerMixin
from sklearn.preprocessing import (FunctionTransformer,StandardScaler)
from sklearn.model_selection import (train_test_split,KFold,StratifiedKFold,cross_val_score,GridSearchCV,learning_curve,validation_curve)
from sklearn.pipeline import Pipeline
from sklearn.tree import DecisionTreeClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.ensemble import (RandomForestClassifier,AdaBoostClassifier,ExtraTreesClassifier,GradientBoostingClassifier)
from sklearn.neighbors import KNeighborsClassifier
from sklearn.naive_bayes import GaussianNB

In [2]:
df.types

NameError: name 'df' is not defined